### ISSUE TITLE
https://techinternships.kxrt.me - new applications all open in the same tab

### ISSUE THREAD

**Issue by TohDeKai** [kxrt/Singapore-Summer2024-TechInternships#130]
Hi, not sure where else to raise this. 

On the https://techinternships.kxrt.me site, when you click apply on any of the listings, a new tab will open if there isn't one already.

However, if a new tab has already been opened previously, when you click apply again, it will just overwrite it. 

https://github.com/kxrt/Singapore-Summer2024-TechInternships/assets/66544431/565cbfc5-3008-48fb-8ae3-9ebae3ca38fa

**Comment by kxrt** [comment]
Hey! Thanks for reporting this - I think I've isolated the issue to where I'm opening new tabs with `window.open` but the target is `blank` instead of `_blank`. I'll deploy a fix to this later today!

**Comment by kxrt** [comment]
Fixed, thank you!
