### ISSUE TITLE
Open Government Products

### ISSUE THREAD

**Issue by kxrt** [kxrt/Singapore-Summer2024-TechInternships#79]
> Automated submission for Open Government Products

Summer
```| Open Government Products | Software Engineering Intern | [Open](https://opengovernmentproducts.recruitee.com/o/software-engineering-intern-offcycle-between-aug-2023-and-apr-2024) | 29 Aug 2023 |```

**Comment by karrui** [comment]
I submitted this. The full title of the internship is technically `Software Engineering Intern (summer; between May and Aug 2024)`, if you want to include that when you open a PR to merge this in.

**Comment by kxrt** [comment]
@karrui Thank you - I'll have another round of updates either tonight or tomorrow!
