### ISSUE TITLE
Rakuten Asia

### ISSUE THREAD

**Issue by kxrt** [kxrt/Singapore-Summer2024-TechInternships#82]
> Automated submission for Rakuten Asia

Summer
```| Rakuten Asia | Software Engineer Intern (Backend) | [Open](https://www.linkedin.com/jobs/collections/recommended/?currentJobId=3691739055) | 30 Aug 2023 |```

**Comment by jasonqiu212** [comment]
Not sure if this is for the summer, since the bottom of the listing reads 2023

**Comment by kxrt** [comment]
Good catch! On further checking, looks like they haven't opened 2024 internship positions yet. Guess they just refreshed the LinkedIn posting.
